name: Tests
on:
  push:
    pull_request:
  concurrency:
    # Group based on workflow name and PR if it exists, if no PR, let it run so carryforward flags work
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
  jobs:
    tests:
      name: Tests
      runs-on: ubuntu-latest
      container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app

  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Running composer install
      run: composer install
