name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: node:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Rebuild the code
        run: |
          npm run build

      - name: Running tests
        run: |
          npm test
