name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: node:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Rebuild the code
        run: |
          # Add your code rebuild commands here
          # For example, if you're using a build script defined in your package.json:
          npm run build
          # Or if you have specific build commands, replace the above line with your custom commands

      - name: Running tests
        run: |
          # Add your test commands here
          # For example, if you're using Jest for testing:
          npm test
          # Or if you're using a different testing framework, use the appropriate test commands
